#!/usr/bin/env node
/* Combine per-set JSON card files into data/cards.js (window.FLASHCARDS).
   Validates schema, dedupes headwords, orders categories, reports stats.
   Usage: node tools/build-cards.js <srcDir> [outFile] */
"use strict";
const fs = require("fs");
const path = require("path");

const SRC = process.argv[2] || path.join(__dirname, "..", "cards-src");
const OUT = process.argv[3] || path.join(__dirname, "..", "data", "cards.js");

const REQUIRED = ["fi", "en", "type", "example_fi", "example_en", "note"];
const TYPES = new Set([
  "substantiivi", "verbi", "adjektiivi", "adverbi",
  "pronomini", "numeraali", "partikkeli", "fraasi"
]);

// Preferred category order (Suomen Mestari themed progression).
const ORDER = [
  "Tervehdykset ja kohteliaisuus", "Perhe ja ihmiset", "Numerot ja määrät",
  "Aika, kellonaika ja viikonpäivät", "Kuukaudet ja vuodenajat",
  "Ruoka ja juoma", "Keittiö ja ruoanlaitto", "Koti ja huonekalut",
  "Vaatteet ja asusteet", "Keho ja terveys", "Värit ja muodot",
  "Sää ja luonto", "Eläimet", "Kaupunki ja liikenne", "Kauppa ja asiointi",
  "Työ ja ammatit", "Koulu ja opiskelu", "Harrastukset ja vapaa-aika",
  "Matkustaminen", "Yhteiskunta ja asuminen", "Yleiset verbit",
  "Adjektiivit", "Adverbit ja paikat", "Kysymyssanat ja pronominit",
  "Yleiset partikkelit ja sidesanat"
];

function fail(msg) { console.error("BUILD ERROR: " + msg); process.exit(1); }

const files = fs.readdirSync(SRC).filter(f => /\.json$/i.test(f)).sort();
if (!files.length) fail("no .json files in " + SRC);

const byName = new Map();     // category -> {category, category_en, cards:[]}
const seenHead = new Map();   // "cat::fi" -> file (dedupe within a category)
const globalHead = new Map(); // fi(lower) -> [categories] (report cross dups)
let warnings = 0;

for (const f of files) {
  const full = path.join(SRC, f);
  let data;
  try { data = JSON.parse(fs.readFileSync(full, "utf8")); }
  catch (e) { fail("invalid JSON in " + f + ": " + e.message); }
  if (!Array.isArray(data)) fail(f + " is not a JSON array of categories");

  for (const cat of data) {
    if (!cat.category || !Array.isArray(cat.cards)) fail(f + ": bad category object");
    let entry = byName.get(cat.category);
    if (!entry) {
      entry = { category: cat.category, category_en: cat.category_en || "", cards: [] };
      byName.set(cat.category, entry);
    }
    for (const card of cat.cards) {
      for (const k of REQUIRED) {
        if (!(k in card) || String(card[k]).trim() === "") {
          console.warn("WARN " + f + " [" + cat.category + "] missing '" + k + "' for '" + (card.fi || "?") + "'");
          warnings++;
        }
      }
      if (card.type && !TYPES.has(card.type)) {
        console.warn("WARN " + f + " unknown type '" + card.type + "' for '" + card.fi + "'");
        warnings++;
      }
      const key = cat.category + "::" + (card.fi || "").toLowerCase();
      if (seenHead.has(key)) { continue; } // silent dedupe within category
      seenHead.set(key, f);
      const low = (card.fi || "").toLowerCase();
      globalHead.set(low, (globalHead.get(low) || []).concat(cat.category));
      entry.cards.push({
        fi: card.fi, en: card.en, type: card.type,
        example_fi: card.example_fi, example_en: card.example_en, note: card.note
      });
    }
  }
}

// Order categories
const cats = Array.from(byName.values()).sort((a, b) => {
  const ia = ORDER.indexOf(a.category), ib = ORDER.indexOf(b.category);
  if (ia === -1 && ib === -1) return a.category.localeCompare(b.category, "fi");
  if (ia === -1) return 1;
  if (ib === -1) return -1;
  return ia - ib;
});

const totalCards = cats.reduce((n, c) => n + c.cards.length, 0);
let crossDups = 0;
for (const [w, list] of globalHead) if (list.length > 1) crossDups++;

const payload = {
  meta: {
    generated: new Date().toISOString().slice(0, 10),
    categories: cats.length,
    cards: totalCards,
    note: "Finnish–English flashcards (Suomen Mestari / YKI themed)."
  },
  categories: cats
};

const banner = "/* Auto-generated by tools/build-cards.js — do not edit by hand.\n" +
  "   " + totalCards + " cards across " + cats.length + " categories. */\n";
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, banner + "window.FLASHCARDS = " + JSON.stringify(payload) + ";\n", "utf8");

console.log("\n== build-cards summary ==");
cats.forEach(c => console.log("  " + String(c.cards.length).padStart(3) + "  " + c.category));
console.log("  ----");
console.log("  " + String(totalCards).padStart(3) + "  TOTAL cards, " + cats.length + " categories");
console.log("  warnings: " + warnings + ", cross-category duplicate headwords: " + crossDups);
console.log("  wrote: " + OUT);
